steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '--tag', '${_IMAGE_REPOSITORY}:build-${BUILD_ID}', '.']
images:
  - '${_IMAGE_REPOSITORY}:build-${BUILD_ID}'
serviceAccount: projects/sql-bigquery-502206/serviceAccounts/boundary-builder@sql-bigquery-502206.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 900s
substitutions:
  _IMAGE_REPOSITORY: us-central1-docker.pkg.dev/sql-bigquery-502206/boundary-images/boundary-adk
